fewer pprint newline

diff --git a/.dot/script/install b/.dot/script/install
--- a/.dot/script/install
+++ b/.dot/script/install
@@ -14,17 +14,15 @@ for script in $(dotfind install.sh); do
   export DOT_TOPIC_LOGFILE_SUFFIX=${topic}${logsuffix}
   pprint step-go "Installing stuff for ${topic}..."
   sh -c "${script}"
-  [[ $? == 0 ]] && pprint info-ok "All is done"
-  [[ $? != 0 ]] && errors+=(${topic}) && pprint info-error "Failed"
-  pprint newline
+  [[ $? == 0 ]] && pprint info-ok -n "All is done"
+  [[ $? != 0 ]] && errors+=(${topic}) && pprint info-error -n "Failed"
 done
 
 # Show summary
 if [[ ${errors} ]]; then
   plogs ${logsuffix} ${errors[@]}
 else
-  pprint step-ok "Everything installed"
-  pprint newline
+  pprint step-ok -n "Everything installed"
 fi
 
 exit 0
diff --git a/.dot/script/install-deps b/.dot/script/install-deps
--- a/.dot/script/install-deps
+++ b/.dot/script/install-deps
@@ -17,9 +17,8 @@ for script in $(dotfind install.dep.sh --priority ${topics}); do
   export DOT_TOPIC_LOGFILE_SUFFIX=${topic}${logsuffix}
   pprint step-go "Checking dependencies from ${topic}..."
   sh -c "${script}"
-  [[ $? == 0 ]] && pprint info-ok "All is ready" && pprint newline
-  [[ $? != 0 ]] && errors+=(${topic}) && pprint info-error "Missing" \
-                                      && pprint newline && break
+  [[ $? == 0 ]] && pprint info-ok -n "All is ready"
+  [[ $? != 0 ]] && errors+=(${topic}) && pprint info-error -n "Missing" && break
 done
 
 # Show summary
@@ -27,7 +26,6 @@ if [[ ${errors} ]]; then
   plogs ${logsuffix} ${errors[@]}
   exit 1
 else
-  pprint step-ok "All dependencies are ready"
-  pprint newline
+  pprint step-ok -n "All dependencies are ready"
   exit 0
 fi
