dot: Move pprint script to .dot/bin

diff --git a/.dot/bin/pprint b/.dot/bin/pprint
--- a/.dot/bin/pprint
+++ b/.dot/bin/pprint
@@ -1,8 +1,9 @@
-#!/bin/bash
-#
+#!/usr/bin/env bash
 # Pretty prints for dotfiles scripts
 
-# Status prints
+
+# -- Status prints -------------------------------------------------------------
+
 pp_fail() {
   printf "$1  [\033[0;31mFAIL\033[0m] $2"
 }
@@ -19,7 +20,9 @@ pp_user() {
   printf "$1  [ \033[0;33m??\033[0m ] $2 "
 }
 
-# Step prints
+
+# -- Step prints ---------------------------------------------------------------
+
 pp_error() {
   printf "$1      \033[0;31m..\033[0m $2"
 }
@@ -36,7 +39,9 @@ pp_warning() {
   printf "$1      \033[0;33m..\033[0m $2"
 }
 
-# Helpers
+
+# -- Helpers -------------------------------------------------------------------
+
 pp_intro() {
   printf "$1  $2\n"
 }
@@ -45,12 +50,16 @@ pp_flush() {
   printf '\n'
 }
 
+# ------------------------------------------------------------------------------
+
+
 usage() {
-  echo "usage: $0 <type> [-r] [string ...]"
-  echo "where <type>:"
-  echo "  fail info success user"
-  echo "  error ok step warning"
-  echo "  flush intro"
+  echo "usage: $0 type [-r] [string]"
+  echo "  type:   fail info success user"
+  echo "          error ok step warning"
+  echo "          flush intro"
+  echo "  -r:     remove previous line break"
+  echo "  string: string to be printed"
 }
 
 # Print type check
@@ -83,7 +92,7 @@ case "$1" in
 
   *)
     usage
-    exit 1
+    exit 1;;
 esac
 shift
 
@@ -92,11 +101,10 @@ if [[ $# > 1 ]]; then
   case "$1" in
     -r)
       SOF="\r\033[2K"
-      shift
-      ;;
+      shift;;
     *)
       usage
-      exit 1
+      exit 1;;
   esac
 else
   SOF="\n"
